//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRWallet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRWallet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string EN_Acc_ChangePwd {
            get {
                return ResourceManager.GetString("EN_Acc_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string EN_Acc_FName {
            get {
                return ResourceManager.GetString("EN_Acc_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string EN_Acc_Header {
            get {
                return ResourceManager.GetString("EN_Acc_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string EN_Acc_LName {
            get {
                return ResourceManager.GetString("EN_Acc_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string EN_Acc_Logout {
            get {
                return ResourceManager.GetString("EN_Acc_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string EN_Acc_SaveChanges {
            get {
                return ResourceManager.GetString("EN_Acc_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string EN_CPwd_CurrPassword {
            get {
                return ResourceManager.GetString("EN_CPwd_CurrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string EN_CPwd_Header {
            get {
                return ResourceManager.GetString("EN_CPwd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string EN_CPwd_NewCPassword {
            get {
                return ResourceManager.GetString("EN_CPwd_NewCPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string EN_CPwd_NewPassword {
            get {
                return ResourceManager.GetString("EN_CPwd_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string EN_CPwd_SaveButton {
            get {
                return ResourceManager.GetString("EN_CPwd_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use.
        /// </summary>
        internal static string EN_Error_Emailinuse {
            get {
                return ResourceManager.GetString("EN_Error_Emailinuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to fill all fields.
        /// </summary>
        internal static string EN_Error_Fields {
            get {
                return ResourceManager.GetString("EN_Error_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string EN_Error_Unknown {
            get {
                return ResourceManager.GetString("EN_Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string EN_Nav_Account {
            get {
                return ResourceManager.GetString("EN_Nav_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string EN_Nav_Addresses {
            get {
                return ResourceManager.GetString("EN_Nav_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string EN_Nav_Dashboard {
            get {
                return ResourceManager.GetString("EN_Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements.
        /// </summary>
        internal static string EN_Nav_Movements {
            get {
                return ResourceManager.GetString("EN_Nav_Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string EN_Nav_Settings {
            get {
                return ResourceManager.GetString("EN_Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string EN_Set_Header {
            get {
                return ResourceManager.GetString("EN_Set_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string EN_Set_Language {
            get {
                return ResourceManager.GetString("EN_Set_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string EN_Set_SaveButton {
            get {
                return ResourceManager.GetString("EN_Set_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string EN_Set_Theme {
            get {
                return ResourceManager.GetString("EN_Set_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_PNG_Prancheta_1 {
            get {
                object obj = ResourceManager.GetObject("Icon PNG_Prancheta 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar Palavra-Passe.
        /// </summary>
        internal static string PT_Acc_ChangePwd {
            get {
                return ResourceManager.GetString("PT_Acc_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Nome.
        /// </summary>
        internal static string PT_Acc_FName {
            get {
                return ResourceManager.GetString("PT_Acc_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        internal static string PT_Acc_Header {
            get {
                return ResourceManager.GetString("PT_Acc_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Nome.
        /// </summary>
        internal static string PT_Acc_LName {
            get {
                return ResourceManager.GetString("PT_Acc_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar sessão.
        /// </summary>
        internal static string PT_Acc_Logout {
            get {
                return ResourceManager.GetString("PT_Acc_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string PT_Acc_SaveChanges {
            get {
                return ResourceManager.GetString("PT_Acc_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-Passe Atual.
        /// </summary>
        internal static string PT_CPwd_CurrPassword {
            get {
                return ResourceManager.GetString("PT_CPwd_CurrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar Palavra-Passe.
        /// </summary>
        internal static string PT_CPwd_Header {
            get {
                return ResourceManager.GetString("PT_CPwd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Palavra-Passe.
        /// </summary>
        internal static string PT_CPwd_NewCPassword {
            get {
                return ResourceManager.GetString("PT_CPwd_NewCPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Palavra-Passe.
        /// </summary>
        internal static string PT_CPwd_NewPassword {
            get {
                return ResourceManager.GetString("PT_CPwd_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar Palavra-Passe.
        /// </summary>
        internal static string PT_CPwd_SaveButton {
            get {
                return ResourceManager.GetString("PT_CPwd_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email em uso.
        /// </summary>
        internal static string PT_Error_Emailinuse {
            get {
                return ResourceManager.GetString("PT_Error_Emailinuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem de preencher todos os campos.
        /// </summary>
        internal static string PT_Error_Fields {
            get {
                return ResourceManager.GetString("PT_Error_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falhou algo na execução.
        /// </summary>
        internal static string PT_Error_Unknown {
            get {
                return ResourceManager.GetString("PT_Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        internal static string PT_Nav_Account {
            get {
                return ResourceManager.GetString("PT_Nav_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços.
        /// </summary>
        internal static string PT_Nav_Addresses {
            get {
                return ResourceManager.GetString("PT_Nav_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string PT_Nav_Dashboard {
            get {
                return ResourceManager.GetString("PT_Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimentos.
        /// </summary>
        internal static string PT_Nav_Movements {
            get {
                return ResourceManager.GetString("PT_Nav_Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string PT_Nav_Settings {
            get {
                return ResourceManager.GetString("PT_Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string PT_Set_Header {
            get {
                return ResourceManager.GetString("PT_Set_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string PT_Set_Language {
            get {
                return ResourceManager.GetString("PT_Set_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string PT_Set_SaveButton {
            get {
                return ResourceManager.GetString("PT_Set_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string PT_Set_Theme {
            get {
                return ResourceManager.GetString("PT_Set_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap receive {
            get {
                object obj = ResourceManager.GetObject("receive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send {
            get {
                object obj = ResourceManager.GetObject("send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
